const { COLOUR } = require('./fashionEnum')

const applianceData = {
  "RET15-1004": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-101F": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1040": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1055": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1088": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: true, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Air Conditioner Accessories": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1002": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1093": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1080": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-102D": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-103C": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: true,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-103B": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: true,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-103A": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: true,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1024": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: true,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1028": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: true,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-102B": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1102": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-103F": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1003": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-101B": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1009": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-107B": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1041": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-107D": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1027": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-102A": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-104D": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1053": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1090": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1023": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1057": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-101A": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1033": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-106E": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1057": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-100A": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1044": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-104E": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-110A": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1021": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: true,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1058": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1026": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1061": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1036": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1082": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: true,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: true, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1065": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1011": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: true, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-106A": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Washing Machine": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: true,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: true, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1067": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1108": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-109D": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1101": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1107": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1105": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1103": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1106": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1069": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1068": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1042": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1043": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1008": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-109B": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: true, value: [] },
    includes: { mandatory: true, value: [] },
    weight: { mandatory: true, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Home Safe": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  Intercom: {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1052": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Smart TV": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: true, value: [] },
    voltage: { mandatory: true, value: [] },
  },
  "Standard TV": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "TV Mount": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "RET15-1078": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Streaming Device": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "TV Accessories": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Virtual Reality Headset": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "3D Glasses": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "3D Modulator": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  Projector: {
    brand: { mandatory: true, value: [] },
    model: { mandatory: true, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Projector Screen": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Projector Mount": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Projector Accessories": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "TV Part": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "TV Remote": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Set Top Box": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "TV Stand": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Video Player": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Digital Photo Frame": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: true, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Home Theatre Projector": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Video Player Accessories": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: false, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Smart Band": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: true, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Smart Glasses": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: true, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Watch Strap Band": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: true, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
  "Wearable Accessories": {
    brand: { mandatory: true, value: [] },
    model: { mandatory: false, value: [] },
    colour: {
      mandatory: false,
      value: COLOUR,
    },
    colour_name: { mandatory: true, value: [] },
    type: { mandatory: false, value: [] },
    special_feature: { mandatory: false, value: [] },
    includes: { mandatory: false, value: [] },
    weight: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    length: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    breadth: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    height: { mandatory: false, value: "/^[0-9]+(.[0-9]{1,2})?$/" },
    refurbished: { mandatory: false, value: [] },
    energy_rating: { mandatory: false, value: [] },
    battery: { mandatory: false, value: [] },
    power_input: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    extended_warranty: { mandatory: false, value: [] },
    installation_detail: { mandatory: false, value: [] },
    wattage: { mandatory: false, value: [] },
    voltage: { mandatory: false, value: [] },
  },
};

module.exports={applianceData}