const groceryObj = {
    brand: {
      mandatory: false,
      value: [],
    },
  };
  
   const groceryJSON = {
    "RET10-1034": groceryObj,
    "RET10-1040": groceryObj,
    "RET10-1043": groceryObj,
    "RET10-102B": groceryObj,
    "Cleaning & RET10-1023": groceryObj,
    "RET10-1004": groceryObj,
    "Pet Care": groceryObj,
    Stationery: groceryObj,
    "RET10-1037": groceryObj,
    "RET10-1038": groceryObj,
    "RET10-1039": groceryObj,
    "RET10-103A": groceryObj,
    "RET10-103B": groceryObj,
    "RET10-1047": groceryObj,
    "RET10-103C": groceryObj,
    "RET10-103D": groceryObj,
    "RET10-1030": groceryObj,
    "RET10-1031": groceryObj,
    "RET10-1032": groceryObj,
    "RET10-1041": groceryObj,
    "RET10-101B": groceryObj,
    Water: groceryObj,
    "RET10-101F": groceryObj,
    "Fruit Juices and Fruit Drinks": groceryObj,
    "RET10-1046": groceryObj,
    "RET10-104A": groceryObj,
    "RET10-1048": groceryObj,
    "RET10-1049": groceryObj,
    "Frozen Vegetables": groceryObj,
    "RET10-1044": groceryObj,
    "RET10-1054": groceryObj,
  };
  
  const healthObj = {
    Brand: {
      mandatory: true,
      value: [],
    },
    Prescription_Required: {
      mandatory: true,
      value: [],
    },
    Usage_Instruction: {
      mandatory: false,
      value: [],
    },
  };
  
   const healthJSON = {
    "RET18-1510": healthObj,
    "Nutrition and Fitness Supplements": healthObj,
    "RET18-1510": healthObj,
    "RET18-1110": healthObj,
    "RET18-1310": healthObj,
    "RET18-1110": healthObj,
    "RET18-1410": healthObj,
    "RET18-1411": healthObj,
    "RET18-1410": healthObj,
    "RET18-1011": healthObj,
    "Baby Care": healthObj,
    "RET18-1011": healthObj,
    "Mobility Aids": healthObj,
    "Medicated Hair Care": healthObj,
    "Medicated Skin Care": healthObj,
    "Speciality Face Cleansers": healthObj,
    "Gastric Care": healthObj,
    "ENT Care": healthObj,
    "RET18-1510": healthObj,
    "RET18-1510": healthObj,
    "RET18-1010": healthObj,
    "Feminine Care": healthObj,
    "Maternity Care": healthObj,
    "Nursing and Feeding": healthObj,
    "Hand Wash": healthObj,
    Sanitizers: healthObj,
    "Baby Care - Wipes and Buds": healthObj,
    "Baby Care - Rash Creams": healthObj,
    "Baby Care - Diapers and Accessories": healthObj,
    "Health and Safety": healthObj,
    "Oral Care": healthObj,
    Contraceptives: healthObj,
    "RET18-1112": healthObj,
    "RET18-1210": healthObj,
    "Wound Care and Dressings": healthObj,
    Surgicals: healthObj,
    "RET18-1510": healthObj,
    "Gift Voucher": healthObj,
  };
  
  const homeObj = {
    Brand: {
      mandatory: true,
      value: [],
    },
    Colour: {
      mandatory: true,
      value: [],
    },
    Colour_Name: {
      mandatory: false,
      value: [],
    },
    Material: {
      mandatory: true,
      value: [],
    },
    Size: {
      mandatory: false,
      value: [],
    },
    Weight: {
      mandatory: false,
      value: [],
    },
    Length: {
      mandatory: false,
      value: [],
    },
    Breadth: {
      mandatory: false,
      value: [],
    },
    Height: {
      mandatory: false,
      value: [],
    },
    Model: {
      mandatory: false,
      value: [],
    },
    Assembly_Required: {
      mandatory: false,
      value: [],
    },
    Care_Instructions: {
      mandatory: false,
      value: [],
    },
    Special_Features: {
      mandatory: false,
      value: [],
    },
  };
  
   const homeJSON = {
    "Home Decor": homeObj,
    "RET16-107A": homeObj,
    "RET16-104C": homeObj,
    "RET16-112C": homeObj,
    "RET16-110E": homeObj,
    "RET16-1131": homeObj,
    "RET16-109C": homeObj,
    "Sports and Fitness Equipment": homeObj,
    "RET16-1136": homeObj,
    Serveware: homeObj,
    "RET16-1132": homeObj,
    "RET16-1132": homeObj,
    "RET16-1159": homeObj,
    "Toys and Games": homeObj,
    Stationery: homeObj,
    "Gift Voucher": {},
  };
  
  const BPCObj = {
    brand: {
      mandatory: true,
      value: [],
    },
    colour: {
      mandatory: false,
      value: [],
    },
    colour_name: {
      mandatory: false,
      value: [],
    },
    gender: {
      mandatory: false,
      value: [],
    },
    concern: {
      mandatory: false,
      value: [],
    },
    ingredient: {
      mandatory: false,
      value: [],
    },
    conscious: {
      mandatory: false,
      value: [],
    },
    preference: {
      mandatory: false,
      value: [],
    },
    formulation: {
      mandatory: false,
      value: [],
    },
    skin_type: {
      mandatory: false,
      value: [],
    },
  };
  
   const BPCJSON = {
    "RET13-1000": BPCObj,
    "RET13-1071": BPCObj,
    "RET13-1142": BPCObj,
    "RET13-1034": BPCObj,
    "RET13-1061": BPCObj,
    "RET13-101A": BPCObj,
    "RET13-112C": BPCObj,
    "RET13-1123": BPCObj,
    "RET13-107A": BPCObj,
    "RET13-1101": BPCObj,
    "RET13-1110": BPCObj,
    "RET13-1104": BPCObj,
    "RET13-1134": BPCObj,
    "RET13-1098": BPCObj,
    "RET13-1118": BPCObj,
    "RET13-104D": BPCObj,
    "RET13-111A": BPCObj,
    "RET13-116B": BPCObj,
    "RET13-1181": BPCObj,
    "RET13-115A": BPCObj,
    "RET13-100F": BPCObj,
    "RET13-118E": BPCObj,
    "RET13-1003": BPCObj,
    "RET13-105C": BPCObj,
    "RET13-1062": BPCObj,
    "RET13-1065": BPCObj,
  };
  
  const AutoPartObj = {
    Brand_Name: {
      mandatory: true,
      value: [],
    },
    Item_Condition: {
      mandatory: true,
      value: [],
    },
    Vehicle_Make: {
      mandatory: true,
      value: [],
    },
    Vehicle_Model: {
      mandatory: true,
      value: [],
    },
    Vehicle_Model_Year: {
      mandatory: true,
      value: [],
    },
    Parts_Origin: {
      mandatory: true,
      value: [],
    },
    New_Arrivals: {
      mandatory: true,
      value: [],
    },
    Material: {
      mandatory: true,
      value: [],
    },
    type: {
      mandatory: true,
      value: [],
    },
  };
  
   const AutoPartsJSON = {
    "RET1A-1000": AutoPartObj,
    "RET1A-1001": AutoPartObj,
    "RET1A-1002": AutoPartObj,
    "RET1A-1003": AutoPartObj,
    "RET1A-1004": AutoPartObj,
    "RET1A-1005": AutoPartObj,
    "RET1A-1006": AutoPartObj,
    "RET1A-1007": AutoPartObj,
    "RET1A-1008": AutoPartObj,
    "RET1A-1009": AutoPartObj,
    "RET1A-100A": AutoPartObj,
    "RET1A-100B": {
      ...AutoPartObj,
      "Number of Blades": { mandatory: true, value: [] },
    },
    "RET1A-100C": AutoPartObj,
    "RET1A-100D": AutoPartObj,
    "RET1A-100E": AutoPartObj,
    "RET1A-100F": AutoPartObj,
    "RET1A-1010": AutoPartObj,
    "RET1A-1011": AutoPartObj,
    "RET1A-1012": AutoPartObj,
    "RET1A-1013": AutoPartObj,
    "RET1A-1014": AutoPartObj,
    "RET1A-1015": {
      ...AutoPartObj,
      Position: { mandatory: true, value: [] },
      Bearing_Type: { mandatory: true, value: [] },
    },
    "RET1A-1016": {
      ...AutoPartObj,
      Bearing_Type: { mandatory: true, value: [] },
    },
    "RET1A-1017": {
      ...AutoPartObj,
      Bearing_Type: { mandatory: true, value: [] },
    },
    "RET1A-1018": {
      ...AutoPartObj,
      Bearing_Type: { mandatory: true, value: [] },
    },
    "RET1A-1019": {
      ...AutoPartObj,
      Bearing_Type: { mandatory: true, value: [] },
    },
    "RET1A-101A": {
      ...AutoPartObj,
      Bearing_Type: { mandatory: true, value: [] },
    },
    "RET1A-101B": {
      ...AutoPartObj,
      Bearing_Type: { mandatory: true, value: [] },
    },
    "RET1A-101C": {
      ...AutoPartObj,
      Bearing_Type: { mandatory: true, value: [] },
    },
    "RET1A-101D": {
      ...AutoPartObj,
      Bearing_Type: { mandatory: true, value: [] },
    },
    "RET1A-101E": {
      ...AutoPartObj,
      Bearing_Type: { mandatory: true, value: [] },
    },
    "RET1A-101F": AutoPartObj,
    "RET1A-1020": AutoPartObj,
    "RET1A-1021": AutoPartObj,
    "RET1A-1022": AutoPartObj,
    "RET1A-1023": AutoPartObj,
    "RET1A-1024": { ...AutoPartObj, Capacity: { mandatory: true, value: [] } },
    "RET1A-1025": { ...AutoPartObj, Capacity: { mandatory: true, value: [] } },
    "RET1A-1026": { ...AutoPartObj, Capacity: { mandatory: true, value: [] } },
    "RET1A-1027": { ...AutoPartObj, Capacity: { mandatory: true, value: [] } },
    "RET1A-1028": { ...AutoPartObj, Capacity: { mandatory: true, value: [] } },
    "RET1A-1029": { ...AutoPartObj, Capacity: { mandatory: true, value: [] } },
    "RET1A-102A": AutoPartObj,
    "RET1A-102B": AutoPartObj,
    "RET1A-102C": AutoPartObj,
    "RET1A-102D": AutoPartObj,
    "RET1A-102E": AutoPartObj,
    "RET1A-102F": AutoPartObj,
    "RET1A-1030": AutoPartObj,
    "RET1A-1031": {
      ...AutoPartObj,
      "Number of Blades": { mandatory: true, value: [] },
    },
    "RET1A-1032": AutoPartObj,
    "RET1A-1033": AutoPartObj,
    "RET1A-1034": AutoPartObj,
    "RET1A-1035": AutoPartObj,
    "RET1A-1036": AutoPartObj,
    "RET1A-1037": AutoPartObj,
    "RET1A-1038": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-1039": AutoPartObj,
    "RET1A-103A": AutoPartObj,
    "RET1A-103B": AutoPartObj,
    "RET1A-103C": AutoPartObj,
    "RET1A-103D": AutoPartObj,
    "RET1A-103E": AutoPartObj,
    "RET1A-103F": AutoPartObj,
    "RET1A-1040": AutoPartObj,
    "RET1A-1041": AutoPartObj,
    "RET1A-1042": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-1043": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-1044": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-1045": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-1046": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-1047": AutoPartObj,
    "RET1A-1048": AutoPartObj,
    "RET1A-1049": AutoPartObj,
    "RET1A-104A": AutoPartObj,
    "RET1A-104B": AutoPartObj,
    "RET1A-104C": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-104D": AutoPartObj,
    "RET1A-104E": AutoPartObj,
    "RET1A-104F": AutoPartObj,
    "RET1A-1050": AutoPartObj,
    "RET1A-1051": {
      ...AutoPartObj,
      Rim: { mandatory: true, value: [] },
      Tyre_Aspect_Ratio: { mandatory: true, value: [] },
      Tyre_Size: { mandatory: true, value: [] },
    },
    "RET1A-1052": {
      ...AutoPartObj,
      Rim: { mandatory: true, value: [] },
      Tyre_Aspect_Ratio: { mandatory: true, value: [] },
      Tyre_Size: { mandatory: true, value: [] },
    },
    "RET1A-1053": {
      ...AutoPartObj,
      Rim: { mandatory: true, value: [] },
      Tyre_Aspect_Ratio: { mandatory: true, value: [] },
      Tyre_Size: { mandatory: true, value: [] },
    },
    "RET1A-1054": {
      ...AutoPartObj,
      Rim: { mandatory: true, value: [] },
      Tyre_Aspect_Ratio: { mandatory: true, value: [] },
      Tyre_Size: { mandatory: true, value: [] },
    },
    "RET1A-1055": AutoPartObj,
    "RET1A-1056": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-1057": AutoPartObj,
    "RET1A-1058": AutoPartObj,
    "RET1A-1059": { ...AutoPartObj, Capacity: { mandatory: true, value: [] } },
    "RET1A-105A": AutoPartObj,
    "RET1A-105B": AutoPartObj,
    "RET1A-105C": AutoPartObj,
    "RET1A-105D": AutoPartObj,
    "RET1A-105E": AutoPartObj,
    "RET1A-105F": AutoPartObj,
    "RET1A-1060": AutoPartObj,
    "RET1A-1061": AutoPartObj,
    "RET1A-1062": AutoPartObj,
    "RET1A-1063": AutoPartObj,
    "RET1A-1064": AutoPartObj,
    "RET1A-1065": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-1066": AutoPartObj,
    "RET1A-1067": AutoPartObj,
    "RET1A-1068": AutoPartObj,
    "RET1A-1069": AutoPartObj,
    "RET1A-106A": AutoPartObj,
    "RET1A-106B": AutoPartObj,
    "RET1A-106C": AutoPartObj,
    "RET1A-106D": AutoPartObj,
    "RET1A-106E": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-106F": AutoPartObj,
    "RET1A-1070": AutoPartObj,
    "RET1A-1071": AutoPartObj,
    "RET1A-1072": AutoPartObj,
    "RET1A-1073": AutoPartObj,
    "RET1A-1074": AutoPartObj,
    "RET1A-1075": AutoPartObj,
    "RET1A-1076": AutoPartObj,
    "RET1A-1077": AutoPartObj,
    "RET1A-1078": AutoPartObj,
    "RET1A-1079": AutoPartObj,
    "RET1A-107A": AutoPartObj,
    "RET1A-107B": AutoPartObj,
    "RET1A-107C": AutoPartObj,
    "RET1A-107D": AutoPartObj,
    "RET1A-107E": AutoPartObj,
    "RET1A-107F": AutoPartObj,
    "RET1A-1080": AutoPartObj,
    "RET1A-1081": AutoPartObj,
    "RET1A-1082": AutoPartObj,
    "RET1A-1083": AutoPartObj,
    "RET1A-1084": AutoPartObj,
    "RET1A-1085": AutoPartObj,
    "RET1A-1086": AutoPartObj,
    "RET1A-1087": AutoPartObj,
    "RET1A-1088": AutoPartObj,
    "RET1A-1089": AutoPartObj,
    "RET1A-108A": AutoPartObj,
    "RET1A-108B": AutoPartObj,
    "RET1A-108C": AutoPartObj,
    "RET1A-108D": AutoPartObj,
    "RET1A-108E": AutoPartObj,
    "RET1A-108F": AutoPartObj,
    "RET1A-1090": AutoPartObj,
    "RET1A-1091": AutoPartObj,
    "RET1A-1092": AutoPartObj,
    "RET1A-1093": AutoPartObj,
    "RET1A-1094": AutoPartObj,
    "RET1A-1095": AutoPartObj,
    "RET1A-1096": AutoPartObj,
    "RET1A-1097": AutoPartObj,
    "RET1A-1098": AutoPartObj,
    "RET1A-1099": AutoPartObj,
    "RET1A-109A": AutoPartObj,
    "RET1A-109B": AutoPartObj,
    "RET1A-109C": AutoPartObj,
    "RET1A-109D": AutoPartObj,
    "RET1A-109E": AutoPartObj,
    "RET1A-109F": AutoPartObj,
    "RET1A-10A0": AutoPartObj,
    "RET1A-10A1": AutoPartObj,
    "RET1A-10A2": AutoPartObj,
    "RET1A-10A3": AutoPartObj,
    "RET1A-10A4": AutoPartObj,
    "RET1A-10A5": AutoPartObj,
    "RET1A-10A6": AutoPartObj,
    "RET1A-10A7": AutoPartObj,
    "RET1A-10A8": AutoPartObj,
    "RET1A-10A9": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10AA": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10AB": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10AC": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10AD": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10AE": AutoPartObj,
    "RET1A-10AF": AutoPartObj,
    "RET1A-10B0": AutoPartObj,
    "RET1A-10B1": AutoPartObj,
    "RET1A-10B2": AutoPartObj,
    "RET1A-10B3": AutoPartObj,
    "RET1A-10B4": AutoPartObj,
    "RET1A-10B5": AutoPartObj,
    "RET1A-10B6": AutoPartObj,
    "RET1A-10B7": AutoPartObj,
    "RET1A-10B8": AutoPartObj,
    "RET1A-10B9": AutoPartObj,
    "RET1A-10BA": AutoPartObj,
    "RET1A-10BB": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10BC": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10BD": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10BE": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10BF": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10C0": AutoPartObj,
    "RET1A-10C1": AutoPartObj,
    "RET1A-10C2": AutoPartObj,
    "RET1A-10C3": AutoPartObj,
    "RET1A-10C4": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10C5": AutoPartObj,
    "RET1A-10C6": AutoPartObj,
    "RET1A-10C7": AutoPartObj,
    "RET1A-10C8": AutoPartObj,
    "RET1A-10C9": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10CA": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10CB": AutoPartObj,
    "RET1A-10CC": { ...AutoPartObj, Position: { mandatory: true, value: [] } },
    "RET1A-10CD": AutoPartObj,
    "RET1A-10CE": AutoPartObj,
    "RET1A-10CF": AutoPartObj,
    "RET1A-10D0": AutoPartObj,
    "RET1A-10D1": AutoPartObj,
    "RET1A-10D2": AutoPartObj,
    "RET1A-10D3": AutoPartObj,
    "RET1A-10D4": AutoPartObj,
    "RET1A-10D5": AutoPartObj,
    "RET1A-10D6": AutoPartObj,
    "RET1A-10D7": AutoPartObj,
    "RET1A-10D8": AutoPartObj,
    "RET1A-10D9": AutoPartObj,
    "RET1A-10DA": AutoPartObj,
    "RET1A-10DB": AutoPartObj,
  };
  
  const ConstructionSuppliesObj = {
    Brand_Name: {
      mandatory: true,
      value: [],
    },
    Model_Number: {
      mandatory: true,
      value: [],
    },
    Generic_Name: {
      mandatory: true,
      value: [],
    },
    Item_Condition: {
      mandatory: true,
      value: [],
    },
    Care_Instructions: {
      mandatory: true,
      value: [],
    },
    Warranty: {
      mandatory: true,
      value: [],
    },
    Length_Breadth_Height: {
      mandatory: true,
      value: [],
    },
  };
  
   const ConstructionSuppliesJSON = {
    "RET1C-1000": ConstructionSuppliesObj,
    "RET1C-1001": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1002": {
      ...ConstructionSuppliesObj,
      Thickness: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1003": {
      ...ConstructionSuppliesObj,
      Diameter: { mandatory: true, value: [] },
    },
    "RET1C-1004": {
      ...ConstructionSuppliesObj,
      Diameter: { mandatory: true, value: [] },
      "Number of Fitting": { mandatory: true, value: [] },
    },
    "RET1C-1005": ConstructionSuppliesObj,
    "RET1C-1006": ConstructionSuppliesObj,
    "RET1C-1007": ConstructionSuppliesObj,
    "RET1C-1008": ConstructionSuppliesObj,
    "RET1C-1009": ConstructionSuppliesObj,
    "RET1C-100A": ConstructionSuppliesObj,
    "RET1C-100B": ConstructionSuppliesObj,
    "RET1C-100C": ConstructionSuppliesObj,
    "RET1C-100D": ConstructionSuppliesObj,
    "RET1C-100E": ConstructionSuppliesObj,
    "RET1C-100F": {
      ...ConstructionSuppliesObj,
      Form_Factor: { mandatory: true, value: [] },
      Grit_Size: { mandatory: true, value: [] },
    },
    "RET1C-1010": {
      ...ConstructionSuppliesObj,
      Grit_Size: { mandatory: true, value: [] },
    },
    "RET1C-1011": ConstructionSuppliesObj,
    "RET1C-1012": ConstructionSuppliesObj,
    "RET1C-1013": {
      ...ConstructionSuppliesObj,
      Form_Factor: { mandatory: true, value: [] },
    },
    "RET1C-1014": ConstructionSuppliesObj,
    "RET1C-1015": {
      ...ConstructionSuppliesObj,
      Hazardous: { mandatory: true, value: [] },
    },
    "RET1C-1016": ConstructionSuppliesObj,
    "RET1C-1017": ConstructionSuppliesObj,
    "RET1C-1018": ConstructionSuppliesObj,
    "RET1C-1019": ConstructionSuppliesObj,
    "RET1C-101A": ConstructionSuppliesObj,
    "RET1C-101B": {
      ...ConstructionSuppliesObj,
      Blade_Material: { mandatory: true, value: [] },
    },
    "RET1C-101C": ConstructionSuppliesObj,
    "RET1C-101D": ConstructionSuppliesObj,
    "RET1C-101E": ConstructionSuppliesObj,
    "RET1C-101F": ConstructionSuppliesObj,
    "RET1C-1020": ConstructionSuppliesObj,
    "RET1C-1021": ConstructionSuppliesObj,
    "RET1C-1022": ConstructionSuppliesObj,
    "RET1C-1023": ConstructionSuppliesObj,
    "RET1C-1024": {
      ...ConstructionSuppliesObj,
      Installation_Type: { mandatory: true, value: [] },
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-1025": ConstructionSuppliesObj,
    "RET1C-1026": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-1027": ConstructionSuppliesObj,
    "RET1C-1028": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-1029": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-102A": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-102B": ConstructionSuppliesObj,
    "RET1C-102C": ConstructionSuppliesObj,
    "RET1C-102D": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-102E": ConstructionSuppliesObj,
    "RET1C-102F": ConstructionSuppliesObj,
    "RET1C-1030": ConstructionSuppliesObj,
    "RET1C-1031": ConstructionSuppliesObj,
    "RET1C-1032": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-1033": ConstructionSuppliesObj,
    "RET1C-1034": ConstructionSuppliesObj,
    "RET1C-1035": ConstructionSuppliesObj,
    "RET1C-1036": ConstructionSuppliesObj,
    "RET1C-1037": ConstructionSuppliesObj,
    "RET1C-1038": ConstructionSuppliesObj,
    "RET1C-1039": ConstructionSuppliesObj,
    "RET1C-103A": ConstructionSuppliesObj,
    "RET1C-103B": ConstructionSuppliesObj,
    "RET1C-103C": {
      ...ConstructionSuppliesObj,
      Installation_Type: { mandatory: true, value: [] },
    },
    "RET1C-103D": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-103E": ConstructionSuppliesObj,
    "RET1C-103F": {
      ...ConstructionSuppliesObj,
      Lid_Included: { mandatory: true, value: [] },
    },
    "RET1C-1040": {
      ...ConstructionSuppliesObj,
      Nozzle_Type: { mandatory: true, value: [] },
    },
    "RET1C-1041": ConstructionSuppliesObj,
    "RET1C-1042": ConstructionSuppliesObj,
    "RET1C-1043": ConstructionSuppliesObj,
    "RET1C-1044": ConstructionSuppliesObj,
    "RET1C-1045": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-1046": ConstructionSuppliesObj,
    "RET1C-1047": ConstructionSuppliesObj,
    "RET1C-1048": ConstructionSuppliesObj,
    "RET1C-1049": ConstructionSuppliesObj,
    "RET1C-104A": ConstructionSuppliesObj,
    "RET1C-104B": ConstructionSuppliesObj,
    "RET1C-104C": ConstructionSuppliesObj,
    "RET1C-104D": ConstructionSuppliesObj,
    "RET1C-104E": ConstructionSuppliesObj,
    "RET1C-104F": ConstructionSuppliesObj,
    "RET1C-1050": ConstructionSuppliesObj,
    "RET1C-1051": ConstructionSuppliesObj,
    "RET1C-1052": ConstructionSuppliesObj,
    "RET1C-1053": ConstructionSuppliesObj,
    "RET1C-1054": ConstructionSuppliesObj,
    "RET1C-1055": ConstructionSuppliesObj,
    "RET1C-1056": ConstructionSuppliesObj,
    "RET1C-1057": {
      ...ConstructionSuppliesObj,
      Form_Factor: { mandatory: true, value: [] },
    },
    "RET1C-1058": ConstructionSuppliesObj,
    "RET1C-1059": ConstructionSuppliesObj,
    "RET1C-105A": ConstructionSuppliesObj,
    "RET1C-105B": ConstructionSuppliesObj,
    "RET1C-105C": ConstructionSuppliesObj,
    "RET1C-105D": ConstructionSuppliesObj,
    "RET1C-105E": {
      ...ConstructionSuppliesObj,
      Lid_Included: { mandatory: true, value: [] },
    },
    "RET1C-105F": ConstructionSuppliesObj,
    "RET1C-1060": ConstructionSuppliesObj,
    "RET1C-1061": ConstructionSuppliesObj,
    "RET1C-1062": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1063": ConstructionSuppliesObj,
    "RET1C-1064": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1065": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1066": {
      ...ConstructionSuppliesObj,
      battery_type: { mandatory: true, value: [] },
    },
    "RET1C-1067": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1068": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1069": ConstructionSuppliesObj,
    "RET1C-106A": ConstructionSuppliesObj,
    "RET1C-106B": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-106C": ConstructionSuppliesObj,
    "RET1C-106D": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-106E": ConstructionSuppliesObj,
    "RET1C-106F": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-1070": ConstructionSuppliesObj,
    "RET1C-1071": ConstructionSuppliesObj,
    "RET1C-1072": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1073": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
      battery_type: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1074": ConstructionSuppliesObj,
    "RET1C-1075": ConstructionSuppliesObj,
    "RET1C-1076": ConstructionSuppliesObj,
    "RET1C-1077": ConstructionSuppliesObj,
    "RET1C-1078": ConstructionSuppliesObj,
    "RET1C-1079": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-107A": ConstructionSuppliesObj,
    "RET1C-107B": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-107C": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-107D": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-107E": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-107F": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1080": ConstructionSuppliesObj,
    "RET1C-1081": ConstructionSuppliesObj,
    "RET1C-1082": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1083": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1084": ConstructionSuppliesObj,
    "RET1C-1085": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1086": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-1087": ConstructionSuppliesObj,
    "RET1C-1088": ConstructionSuppliesObj,
    "RET1C-1089": ConstructionSuppliesObj,
    "RET1C-108A": ConstructionSuppliesObj,
    "RET1C-108B": ConstructionSuppliesObj,
    "RET1C-108C": ConstructionSuppliesObj,
    "RET1C-108D": ConstructionSuppliesObj,
    "RET1C-108E": ConstructionSuppliesObj,
    "RET1C-108F": ConstructionSuppliesObj,
    "RET1C-1090": ConstructionSuppliesObj,
    "RET1C-1091": ConstructionSuppliesObj,
    "RET1C-1092": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-1093": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-1094": ConstructionSuppliesObj,
    "RET1C-1095": ConstructionSuppliesObj,
    "RET1C-1096": ConstructionSuppliesObj,
    "RET1C-1097": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-1098": {
      ...ConstructionSuppliesObj,
      Thickness: { mandatory: true, value: [] },
    },
    "RET1C-1099": ConstructionSuppliesObj,
    "RET1C-109A": ConstructionSuppliesObj,
    "RET1C-109B": {
      ...ConstructionSuppliesObj,
      Power_Output: {
        mandatory: true,
        value: [],
      },
    },
    "RET1C-109C": ConstructionSuppliesObj,
    "RET1C-109D": ConstructionSuppliesObj,
    "RET1C-109E": ConstructionSuppliesObj,
    "RET1C-109F": ConstructionSuppliesObj,
    "RET1C-10A0": {
      ...ConstructionSuppliesObj,
      Blade_Material: { mandatory: true, value: [] },
    },
    "RET1C-10A1": ConstructionSuppliesObj,
    "RET1C-10A2": ConstructionSuppliesObj,
    "RET1C-10A3": {
      ...ConstructionSuppliesObj,
      Blade_Material: { mandatory: true, value: [] },
    },
    "RET1C-10A4": ConstructionSuppliesObj,
    "RET1C-10A5": {
      ...ConstructionSuppliesObj,
      Blade_Material: { mandatory: true, value: [] },
    },
    "RET1C-10A6": {
      ...ConstructionSuppliesObj,
      Blade_Material: { mandatory: true, value: [] },
    },
    "RET1C-10A7": ConstructionSuppliesObj,
    "RET1C-10A8": ConstructionSuppliesObj,
    "RET1C-10A9": {
      ...ConstructionSuppliesObj,
      Form_Factor: { mandatory: true, value: [] },
    },
    "RET1C-10AA": ConstructionSuppliesObj,
    "RET1C-10AB": ConstructionSuppliesObj,
    "RET1C-10AC": {
      ...ConstructionSuppliesObj,
      Form_Factor: { mandatory: true, value: [] },
    },
    "RET1C-10AD": ConstructionSuppliesObj,
    "RET1C-10AE": ConstructionSuppliesObj,
    "RET1C-10AF": ConstructionSuppliesObj,
    "RET1C-10B0": ConstructionSuppliesObj,
  };
  
  const HardwareObj = {
    Brand_Name: {
      mandatory: true,
      value: [],
    },
    Product_Name: {
      mandatory: true,
      value: [],
    },
    Product_Dimensions: {
      mandatory: true,
      value: [],
    },
    Weight: {
      mandatory: true,
      value: [],
    },
    Shipping_Weight: {
      mandatory: true,
      value: [],
    },
    Material: {
      mandatory: true,
      value: [],
    },
    Manufacturer_Name: {
      mandatory: true,
      value: [],
    },
    Size: {
      mandatory: true,
      value: [],
    },
    Series: {
      mandatory: true,
      value: [],
    },
    Warranty: {
      mandatory: true,
      value: [],
    },
    Finish: {
      mandatory: true,
      value: [],
    },
  };
  
   const HardwareJSON = {
    "RET1B-1000": { ...HardwareObj, connection: { mandatory: true, value: [] } },
    "RET1B-1001": { ...HardwareObj, connection: { mandatory: true, value: [] } },
    "RET1B-1002": {
      ...HardwareObj,
      Product_Shape: { mandatory: true, value: [] },
    },
    "RET1B-1003": { ...HardwareObj, Head_Style: { mandatory: true, value: [] } },
    "RET1B-1004": HardwareObj,
    "RET1B-1005": HardwareObj,
    "RET1B-1006": HardwareObj,
    "RET1B-1007": HardwareObj,
    "RET1B-1008": HardwareObj,
    "RET1B-1009": HardwareObj,
    "RET1B-100A": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-100B": HardwareObj,
    "RET1B-100C": HardwareObj,
    "RET1B-100D": {
      ...HardwareObj,
      Capacity: { mandatory: true, value: [] },
      Product_Shape: { mandatory: true, value: [] },
    },
    "RET1B-100E": { ...HardwareObj, Capacity: { mandatory: true, value: [] } },
    "RET1B-100F": { ...HardwareObj, Capacity: { mandatory: true, value: [] } },
    "RET1B-1010": HardwareObj,
    "RET1B-1011": HardwareObj,
    "RET1B-1012": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
      Power_Supply: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1013": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
      Power_Supply: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      Efficient_Grade: { mandatory: true, value: [] },
      IP_Rating: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1014": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
      Power_Supply: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      IP_Rating: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1015": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
      Power_Supply: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      IP_Rating: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1016": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
      Power_Supply: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      IP_Rating: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1017": {
      ...HardwareObj,
      Wattage: { mandatory: true, value: [] },
    },
    "RET1B-1018": {
      ...HardwareObj,
      Wattage: { mandatory: true, value: [] },
    },
    "RET1B-1019": {
      ...HardwareObj,
      Wattage: { mandatory: true, value: [] },
    },
    "RET1B-101A": {
      ...HardwareObj,
      Wattage: { mandatory: true, value: [] },
    },
    "RET1B-101B": {
      ...HardwareObj,
      Water_Resistance: { mandatory: true, value: [] },
      Fire_Resistant: { mandatory: true, value: [] },
    },
    "RET1B-101C": {
      ...HardwareObj,
      Water_Resistance: { mandatory: true, value: [] },
      Fire_Resistant: { mandatory: true, value: [] },
    },
    "RET1B-101D": HardwareObj,
    "RET1B-101E": HardwareObj,
    "RET1B-101F": HardwareObj,
    "RET1B-1020": HardwareObj,
    "RET1B-1021": {
      ...HardwareObj,
      Water_Resistance: { mandatory: true, value: [] },
    },
    "RET1B-1022": HardwareObj,
    "RET1B-1023": {
      ...HardwareObj,
      Water_Resistance: { mandatory: true, value: [] },
    },
    "RET1B-1024": HardwareObj,
    "RET1B-1025": HardwareObj,
    "RET1B-1026": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
      Power_Supply: { mandatory: true, value: [] },
      Audiable_Range: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
      Compatible_Devices: { mandatory: true, value: [] },
    },
    "RET1B-1027": HardwareObj,
    "RET1B-1028": HardwareObj,
    "RET1B-1029": {
      ...HardwareObj,
      Fire_Resistant: { mandatory: true, value: [] },
      fire_rating: { mandatory: true, value: [] },
    },
    "RET1B-102A": { ...HardwareObj, Capacity: { mandatory: true, value: [] } },
    "RET1B-102B": HardwareObj,
    "RET1B-102C": HardwareObj,
    "RET1B-102D": HardwareObj,
    "RET1B-102E": HardwareObj,
    "RET1B-102F": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
      Power_Supply: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1030": HardwareObj,
    "RET1B-1031": HardwareObj,
    "RET1B-1032": HardwareObj,
    "RET1B-1033": HardwareObj,
    "RET1B-1034": HardwareObj,
    "RET1B-1035": HardwareObj,
    "RET1B-1036": HardwareObj,
    "RET1B-1037": HardwareObj,
    "RET1B-1038": HardwareObj,
    "RET1B-1039": HardwareObj,
    "RET1B-103A": { ...HardwareObj, IP_Rating: { mandatory: true, value: [] } },
    "RET1B-103B": { ...HardwareObj, IP_Rating: { mandatory: true, value: [] } },
    "RET1B-103C": { ...HardwareObj, IP_Rating: { mandatory: true, value: [] } },
    "RET1B-103D": { ...HardwareObj, IP_Rating: { mandatory: true, value: [] } },
    "RET1B-103E": HardwareObj,
    "RET1B-103F": HardwareObj,
    "RET1B-1040": HardwareObj,
    "RET1B-1041": HardwareObj,
    "RET1B-1042": {
      ...HardwareObj,
      Power_Source: { mandatory: true, value: [] },
      Fire_Resistant: { mandatory: true, value: [] },
      Length: { mandatory: true, value: [] },
    },
    "RET1B-1043": {
      ...HardwareObj,
      Power_Source: { mandatory: true, value: [] },
      Length: { mandatory: true, value: [] },
    },
    "RET1B-1044": {
      ...HardwareObj,
      Power_Source: { mandatory: true, value: [] },
      Length: { mandatory: true, value: [] },
    },
    "RET1B-1045": {
      ...HardwareObj,
      Power_Source: { mandatory: true, value: [] },
      Length: { mandatory: true, value: [] },
    },
    "RET1B-1046": {
      ...HardwareObj,
      Power_Source: { mandatory: true, value: [] },
      Length: { mandatory: true, value: [] },
    },
    "RET1B-1047": {
      ...HardwareObj,
      Power_Source: { mandatory: true, value: [] },
      Length: { mandatory: true, value: [] },
    },
    "RET1B-1048": {
      ...HardwareObj,
      Power_Source: { mandatory: true, value: [] },
      Length: { mandatory: true, value: [] },
    },
    "RET1B-1049": {
      ...HardwareObj,
      Power_Source: { mandatory: true, value: [] },
      Length: { mandatory: true, value: [] },
    },
    "RET1B-104A": {
      ...HardwareObj,
      Power_Source: { mandatory: true, value: [] },
    },
    "RET1B-104B": HardwareObj,
    "RET1B-104C": {
      ...HardwareObj,
      Capacity: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-104D": HardwareObj,
    "RET1B-104E": {
      ...HardwareObj,
      Power_Source: { mandatory: true, value: [] },
      Fire_Resistant: { mandatory: true, value: [] },
    },
    "RET1B-104F": HardwareObj,
    "RET1B-1050": HardwareObj,
    "RET1B-1051": {
      ...HardwareObj,
      Fire_Resistant: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1052": { ...HardwareObj, voltage: { mandatory: true, value: [] } },
    "RET1B-1053": HardwareObj,
    "RET1B-1054": {
      ...HardwareObj,
      Fire_Resistant: { mandatory: true, value: [] },
    },
    "RET1B-1055": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Efficient_Grade: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1056": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Moutning_Type: { mandatory: true, value: [] },
      Efficient_Grade: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1057": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Moutning_Type: { mandatory: true, value: [] },
      Efficient_Grade: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1058": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Moutning_Type: { mandatory: true, value: [] },
      Efficient_Grade: { mandatory: true, value: [] },
      Water_Resistance: { mandatory: true, value: [] },
      Connectivity: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1059": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Moutning_Type: { mandatory: true, value: [] },
      Efficient_Grade: { mandatory: true, value: [] },
      Water_Resistance: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-105A": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Efficient_Grade: { mandatory: true, value: [] },
      Connectivity: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-105B": { ...HardwareObj, IP_Rating: { mandatory: true, value: [] } },
    "RET1B-105C": { ...HardwareObj, IP_Rating: { mandatory: true, value: [] } },
    "RET1B-105D": HardwareObj,
    "RET1B-105E": {
      ...HardwareObj,
      IP_Rating: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-105F": HardwareObj,
    "RET1B-1060": HardwareObj,
    "RET1B-1061": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
    },
    "RET1B-1062": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
    },
    "RET1B-1063": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
    },
    "RET1B-1064": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
    },
    "RET1B-1065": {
      ...HardwareObj,
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-1066": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-1067": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
    },
    "RET1B-1068": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
    },
    "RET1B-1069": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-106A": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-106B": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-106C": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-106D": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-106E": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-106F": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-1070": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-1071": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-1072": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-1073": {
      ...HardwareObj,
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-1074": {
      ...HardwareObj,
      battery_type: { mandatory: true, value: [] },
      battery_life: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-1075": HardwareObj,
    "RET1B-1076": HardwareObj,
    "RET1B-1077": HardwareObj,
    "RET1B-1078": {
      ...HardwareObj,
      Output: { mandatory: true, value: [] },
    },
    "RET1B-1079": { ...HardwareObj, voltage: { mandatory: true, value: [] } },
    "RET1B-107A": { ...HardwareObj, voltage: { mandatory: true, value: [] } },
    "RET1B-107B": { ...HardwareObj, voltage: { mandatory: true, value: [] } },
    "RET1B-107C": { ...HardwareObj, voltage: { mandatory: true, value: [] } },
    "RET1B-107D": { ...HardwareObj, voltage: { mandatory: true, value: [] } },
    "RET1B-107E": {
      ...HardwareObj,
      Output: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-107F": {
      ...HardwareObj,
      Output: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1080": {
      ...HardwareObj,
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1081": {
      ...HardwareObj,
      Capacity: { mandatory: true, value: [] },
      micron_rating: { mandatory: true, value: [] },
    },
    "RET1B-1082": {
      ...HardwareObj,
      Capacity: { mandatory: true, value: [] },
      micron_rating: { mandatory: true, value: [] },
    },
    "RET1B-1083": {
      ...HardwareObj,
      micron_rating: { mandatory: true, value: [] },
    },
    "RET1B-1084": {
      ...HardwareObj,
      micron_rating: { mandatory: true, value: [] },
    },
    "RET1B-1085": {
      ...HardwareObj,
      micron_rating: { mandatory: true, value: [] },
    },
    "RET1B-1086": HardwareObj,
    "RET1B-1087": HardwareObj,
    "RET1B-1088": HardwareObj,
    "RET1B-1089": HardwareObj,
    "RET1B-108A": HardwareObj,
    "RET1B-108B": HardwareObj,
    "RET1B-108C": { ...HardwareObj, Length: { mandatory: true, value: [] } },
    "RET1B-108D": HardwareObj,
    "RET1B-108E": HardwareObj,
    "RET1B-108F": HardwareObj,
    "RET1B-1090": HardwareObj,
    "RET1B-1091": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
    },
    "RET1B-1092": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Connectivity: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1093": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Connectivity: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-1094": {
      ...HardwareObj,
      Capacity: { mandatory: true, value: [] },
      Power_Supply: { mandatory: true, value: [] },
      Length: { mandatory: true, value: [] },
    },
    "RET1B-1095": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
    },
    "RET1B-1096": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
    },
    "RET1B-1097": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
    },
    "RET1B-1098": HardwareObj,
    "RET1B-1099": HardwareObj,
    "RET1B-109A": HardwareObj,
    "RET1B-109B": HardwareObj,
    "RET1B-109C": HardwareObj,
    "RET1B-109D": HardwareObj,
    "RET1B-109E": HardwareObj,
    "RET1B-109F": HardwareObj,
    "RET1B-10A0": HardwareObj,
    "RET1B-10A1": { ...HardwareObj, voltage: { mandatory: true, value: [] } },
    "RET1B-10A2": {
      ...HardwareObj,
      Output: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10A3": {
      ...HardwareObj,
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10A4": HardwareObj,
    "RET1B-10A5": HardwareObj,
    "RET1B-10A6": {
      ...HardwareObj,
      power_requirement: { mandatory: true, value: [] },
    },
    "RET1B-10A7": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10A8": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10A9": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10AA": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10AB": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10AC": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10AD": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10AE": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10AF": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10B0": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10B1": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10B2": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10B3": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10B4": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10B5": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      Wattage: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10B6": {
      ...HardwareObj,
      connection: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      voltage: { mandatory: true, value: [] },
    },
    "RET1B-10B7": {
      ...HardwareObj,
      Capacity: { mandatory: true, value: [] },
      Product_Shape: { mandatory: true, value: [] },
    },
    "RET1B-10B8": {
      ...HardwareObj,
      Product_Shape: { mandatory: true, value: [] },
    },
    "RET1B-10B9": {
      ...HardwareObj,
      Product_Shape: { mandatory: true, value: [] },
    },
    "RET1B-10BA": {
      ...HardwareObj,
      Product_Shape: { mandatory: true, value: [] },
    },
    "RET1B-10BB": {
      ...HardwareObj,
      Product_Shape: { mandatory: true, value: [] },
    },
    "RET1B-10BC": {
      ...HardwareObj,
      Capacity: { mandatory: true, value: [] },
      Product_Shape: { mandatory: true, value: [] },
    },
    "RET1B-10BD": HardwareObj,
    "RET1B-10BE": HardwareObj,
    "RET1B-10BF": HardwareObj,
    "RET1B-10C0": HardwareObj,
    "RET1B-10C1": {
      ...HardwareObj,
      Water_Resistance: { mandatory: true, value: [] },
    },
    "RET1B-10C2": HardwareObj,
    "RET1B-10C3": HardwareObj,
    "RET1B-10C4": HardwareObj,
    "RET1B-10C5": HardwareObj,
    "RET1B-10C6": HardwareObj,
    "RET1B-10C7": HardwareObj,
    "RET1B-10C8": HardwareObj,
    "RET1B-10C9": HardwareObj,
    "RET1B-10CA": HardwareObj,
    "RET1B-10CB": HardwareObj,
    "RET1B-10CC": HardwareObj,
    "RET1B-10CD": {
      ...HardwareObj,
      Capacity: { mandatory: true, value: [] },
      RPM: { mandatory: true, value: [] },
    },
    "RET1B-10CE": {
      ...HardwareObj,
      Capacity: { mandatory: true, value: [] },
      RPM: { mandatory: true, value: [] },
    },
    "RET1B-10CF": HardwareObj,
    "RET1B-10D0": HardwareObj,
    "RET1B-10D1": HardwareObj,
    "RET1B-10D2": HardwareObj,
    "RET1B-10D3": HardwareObj,
    "RET1B-10D4": HardwareObj,
    "RET1B-10D5": HardwareObj,
    "RET1B-10D6": HardwareObj,
    "RET1B-10D7": {
      ...HardwareObj,
      RPM: { mandatory: true, value: [] },
    },
    "RET1B-10D8": HardwareObj,
    "RET1B-10D9": HardwareObj,
    "RET1B-10DA": HardwareObj,
    "RET1B-10DB": HardwareObj,
    "RET1B-10DC": HardwareObj,
    "RET1B-10DD": HardwareObj,
    "RET1B-10DE": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
    },
    "RET1B-10DF": { ...HardwareObj, heat_time: { mandatory: true, value: [] } },
    "RET1B-10E0": HardwareObj,
    "RET1B-10E1": HardwareObj,
    "RET1B-10E2": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
      Output: { mandatory: true, value: [] },
    },
    "RET1B-10E3": {
      ...HardwareObj,
      Capacity: { mandatory: true, value: [] },
      Connectivity: { mandatory: true, value: [] },
      Resolution: { mandatory: true, value: [] },
      Length: { mandatory: true, value: [] },
    },
    "RET1B-10E4": HardwareObj,
    "RET1B-10E5": HardwareObj,
    "RET1B-10E6": HardwareObj,
    "RET1B-10E7": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
      Power_Supply: { mandatory: true, value: [] },
    },
    "RET1B-10E8": HardwareObj,
    "RET1B-10E9": HardwareObj,
    "RET1B-10EA": HardwareObj,
    "RET1B-10EB": { ...HardwareObj, Capacity: { mandatory: true, value: [] } },
    "RET1B-10EC": HardwareObj,
    "RET1B-10ED": {
      ...HardwareObj,
      Capacity: { mandatory: true, value: [] },
      fire_rating: { mandatory: true, value: [] },
    },
    "RET1B-10EE": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
      Resolution: { mandatory: true, value: [] },
      Video_Output: { mandatory: true, value: [] },
      Compatible_Devices: { mandatory: true, value: [] },
    },
    "RET1B-10EF": {
      ...HardwareObj,
      Audiable_Range: { mandatory: true, value: [] },
      Connectivity: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
    },
    "RET1B-10F0": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
      Connectivity: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
      Video_Output: { mandatory: true, value: [] },
      Compatible_Devices: { mandatory: true, value: [] },
      Touchscreen: { mandatory: true, value: [] },
    },
    "RET1B-10F1": {
      ...HardwareObj,
      Audiable_Range: { mandatory: true, value: [] },
      Connectivity: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-10F2": HardwareObj,
    "RET1B-10F3": HardwareObj,
    "RET1B-10F4": {
      ...HardwareObj,
      Connectivity: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      Resolution: { mandatory: true, value: [] },
      Video_Output: { mandatory: true, value: [] },
      Compatible_Devices: { mandatory: true, value: [] },
      Touchscreen: { mandatory: true, value: [] },
    },
    "RET1B-10F5": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
    },
    "RET1B-10F6": {
      ...HardwareObj,
      Power_Supply: { mandatory: true, value: [] },
      Connectivity: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      Compatible_Devices: { mandatory: true, value: [] },
      Touchscreen: { mandatory: true, value: [] },
      Identification_method: { mandatory: true, value: [] },
    },
    "RET1B-10F7": {
      ...HardwareObj,
      battery_type: { mandatory: true, value: [] },
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-10F8": {
      ...HardwareObj,
      battery_included: { mandatory: true, value: [] },
    },
    "RET1B-10F9": {
      ...HardwareObj,
      Flash_Light_Included: { mandatory: true, value: [] },
      Power_Supply: { mandatory: true, value: [] },
      Moutning_Type: { mandatory: true, value: [] },
      Water_Resistance: { mandatory: true, value: [] },
      Connectivity: { mandatory: true, value: [] },
      battery_type: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      Resolution: { mandatory: true, value: [] },
      Video_Output: { mandatory: true, value: [] },
      Compatible_Devices: { mandatory: true, value: [] },
    },
    "RET1B-10FA": {
      ...HardwareObj,
      Connectivity: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      Compatible_Devices: { mandatory: true, value: [] },
      Touchscreen: { mandatory: true, value: [] },
    },
    "RET1B-10FB": {
      ...HardwareObj,
      Connectivity: { mandatory: true, value: [] },
      power_requirement: { mandatory: true, value: [] },
      Compatible_Devices: { mandatory: true, value: [] },
      Touchscreen: { mandatory: true, value: [] },
    },
    "RET1B-10FC": HardwareObj,
  };
  
  const ChemicalObj = {
    Brand_Name: {
      mandatory: true,
      value: [],
    },
    Model_Number: {
      mandatory: true,
      value: [],
    },
    Chemical_Name: {
      mandatory: true,
      value: [],
    },
    Size: {
      mandatory: true,
      value: [],
    },
    Brand_Name: {
      mandatory: true,
      value: [],
    },
    Colour: {
      mandatory: true,
      value: [],
    },
    Material: {
      mandatory: true,
      value: [],
    },
    Manufacturer_Name: {
      mandatory: true,
      value: [],
    },
    Care_Instructions: {
      mandatory: true,
      value: [],
    },
    Capacity: {
      mandatory: true,
      value: [],
    },
    Product_Dimensions: {
      mandatory: true,
      value: [],
    },
    Active_Ingredient: {
      mandatory: true,
      value: [],
    },
    Weight: {
      mandatory: true,
      value: [],
    },
  };
  
   const ChemicalJSON = {
    "RET1D-1000": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1001": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1002": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1003": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1004": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1005": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1006": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1007": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1008": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1009": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-100A": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-100B": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-100C": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-100D": {
      ...ChemicalObj,
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-100E": {
      ...ChemicalObj,
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-100F": {
      ...ChemicalObj,
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1010": {
      ...ChemicalObj,
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1011": {
      ...ChemicalObj,
      Included_Components: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1012": {
      ...ChemicalObj,
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1013": {
      ...ChemicalObj,
      Included_Components: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1014": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
      Included_Components: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1015": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1016": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1017": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1018": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1019": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-101A": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-101B": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Included_Components: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-101C": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Included_Components: { mandatory: true, value: [] },
    },
    "RET1D-101D": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-101E": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-101F": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1020": {
      ...ChemicalObj,
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      checmical_formula: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1021": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
      Concentration: { mandatory: true, value: [] },
    },
    "RET1D-1022": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1023": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
      Included_Components: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1024": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
      Product_Dimensions: { mandatory: true, value: [] },
      Item_Form: { mandatory: true, value: [] },
    },
    "RET1D-1025": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
      Product_Dimensions: { mandatory: true, value: [] },
    },
    "RET1D-1026": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
      Product_Dimensions: { mandatory: true, value: [] },
    },
    "RET1D-1027": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
    },
    "RET1D-1028": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
    },
    "RET1D-1029": {
      ...ChemicalObj,
      Container_Type: { mandatory: true, value: [] },
    },
    "RET1D-102A": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
      Container_Type: { mandatory: true, value: [] },
      Product_Dimensions: { mandatory: true, value: [] },
    },
    "RET1D-102B": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
      Container_Type: { mandatory: true, value: [] },
      Product_Dimensions: { mandatory: true, value: [] },
    },
    "RET1D-102C": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
      Container_Type: { mandatory: true, value: [] },
      Product_Dimensions: { mandatory: true, value: [] },
    },
    "RET1D-102D": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      Concentration: { mandatory: true, value: [] },
    },
    "RET1D-102E": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      Concentration: { mandatory: true, value: [] },
    },
    "RET1D-102F": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
      Chemical_State: { mandatory: true, value: [] },
      Container_Type: { mandatory: true, value: [] },
      Concentration: { mandatory: true, value: [] },
    },
    "RET1D-1030": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
      Container_Type: { mandatory: true, value: [] },
      Concentration: { mandatory: true, value: [] },
    },
    "RET1D-1031": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
      Container_Type: { mandatory: true, value: [] },
      Concentration: { mandatory: true, value: [] },
    },
    "RET1D-1032": { ...ChemicalObj, Weight: { mandatory: false, value: [] } },
    "RET1D-1033": { ...ChemicalObj, Weight: { mandatory: false, value: [] } },
    "RET1D-1034": { ...ChemicalObj, Weight: { mandatory: false, value: [] } },
    "RET1D-1035": { ...ChemicalObj, Weight: { mandatory: false, value: [] } },
    "RET1D-1036": { ...ChemicalObj, Weight: { mandatory: false, value: [] } },
    "RET1D-1037": { ...ChemicalObj, Weight: { mandatory: false, value: [] } },
    "RET1D-1038": { ...ChemicalObj, Weight: { mandatory: false, value: [] } },
    "RET1D-1039": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
      Product_Dimensions: { mandatory: true, value: [] },
    },
    "RET1D-103A": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
      Product_Dimensions: { mandatory: true, value: [] },
    },
    "RET1D-103B": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
      Product_Dimensions: { mandatory: true, value: [] },
    },
    "RET1D-103C": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
      Product_Dimensions: { mandatory: true, value: [] },
    },
    "RET1D-103D": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
    },
    "RET1D-103E": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
    },
    "RET1D-103F": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
    },
    "RET1D-1040": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
    },
    "RET1D-1041": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
    },
    "RET1D-1042": {
      ...ChemicalObj,
      Weight: { mandatory: false, value: [] },
    },
  };

  module.exports={groceryJSON,healthJSON,BPCJSON,AutoPartsJSON,ConstructionSuppliesJSON,ChemicalJSON,HardwareJSON,homeJSON}