const IV_LENGTH_IN_BITS = 96;
const KEY_LENGTH_IN_BITS = 2048;
const AUTH_TAG_LENGTH_IN_BITS = 128; //CANNOT BE CHANGED FOR AES-256-GCM

module.exports = {
  IV_LENGTH_IN_BITS,
  AUTH_TAG_LENGTH_IN_BITS,
  KEY_LENGTH_IN_BITS,
};
