const IV_LENGTH_IN_BITS = 96;
const AUTH_TAG_LENGTH_IN_BITS = 128; //CANNOT BE CHANGED FOR AES-256-GCM
const KEY_PAIR_GENERATION_ALGORITHM = "x25519";
const ENCRYPT_DECRYPT_ALGORITHM = "aes-256-gcm";
const KEY_STRING_FORMAT = "base64";

module.exports = {
  IV_LENGTH_IN_BITS,
  AUTH_TAG_LENGTH_IN_BITS,
  KEY_PAIR_GENERATION_ALGORITHM,
  ENCRYPT_DECRYPT_ALGORITHM,
  KEY_STRING_FORMAT,
};
